"""empty message

Revision ID: 52838e37ed17
Revises: a3ae6e547e98
Create Date: 2026-04-08 16:40:49.119717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52838e37ed17'
down_revision = 'a3ae6e547e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_viaje', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_viaje'], ['viaje.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('id_viaje', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_viaje'], ['viaje.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('id_viaje', sa.Integer(), nullable=False),
    sa.Column('id_pagador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pagador'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_viaje'], ['viaje.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deuda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('id_deudor', sa.Integer(), nullable=False),
    sa.Column('id_acreedor', sa.Integer(), nullable=False),
    sa.Column('id_gasto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_acreedor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_deudor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_gasto'], ['gasto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=500), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chat'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensaje')
    op.drop_table('deuda')
    op.drop_table('gasto')
    op.drop_table('documento')
    op.drop_table('chat')
    # ### end Alembic commands ###
