"""empty message

Revision ID: a113de1b1d92
Revises: a3ae6e547e98
Create Date: 2026-04-08 17:11:17.369466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a113de1b1d92'
down_revision = 'a3ae6e547e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desciption', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('TRANSPORT', 'LODGING', 'FOOD', 'ACTIVITIES', 'OTHERS', name='categorytypes'), nullable=False),
    sa.Column('id_viaje', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_viaje'], ['viaje.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'id_viaje')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gasto')
    # ### end Alembic commands ###
