"""empty message

Revision ID: a3ae6e547e98
Revises: f9b6109c894e
Create Date: 2026-04-06 19:22:10.304592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ae6e547e98'
down_revision = 'f9b6109c894e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('hour', sa.Time(), nullable=False),
    sa.Column('starting_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=150), nullable=False),
    sa.Column('id_viaje', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_viaje'], ['viaje.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'id_viaje')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerario')
    # ### end Alembic commands ###
