"""empty message

Revision ID: dd2187fa5765
Revises: 1a8004bec489
Create Date: 2026-04-06 18:09:50.559822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2187fa5765'
down_revision = '1a8004bec489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('state', sa.Enum('FINISHED', 'ONGOING', 'PLANNING', name='statetypes'), nullable=False),
    sa.Column('starting_date', sa.Date(), nullable=False),
    sa.Column('ending_date', sa.Date(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viaje')
    # ### end Alembic commands ###
