"""empty message

Revision ID: f9b6109c894e
Revises: dd2187fa5765
Create Date: 2026-04-06 19:09:26.923084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b6109c894e'
down_revision = 'dd2187fa5765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viajero',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_viaje', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_viaje'], ['viaje.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_user', 'id_viaje')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viajero')
    # ### end Alembic commands ###
